# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="clean"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(brew git github heroku node npm osx ruby rvm vi-mode)
plugins=(git github heroku node npm ruby rvm terminator debian)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Set up PATHs based on local installs
PATH="$HOME/local/bin:/opt/local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
LD_LIBRARY_PATH="/opt/local/lib:/usr/local/lib:/usr/lib"
if [ -d $HOME/local ]; then
  for i in $HOME/local/*; do
    [ -d $i/bin ] && PATH="${i}/bin:${PATH}"
    [ -d $i/sbin ] && PATH="${i}/sbin:${PATH}"
    [ -d $i/include ] && CPATH="${i}/include:${CPATH}"
    [ -d $i/lib ] && LD_LIBRARY_PATH="${i}/lib:${LD_LIBRARY_PATH}"
    [ -d $i/lib/pkgconfig ] && PKG_CONFIG_PATH="${i}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    [ -d $i/share/man ] && MANPATH="${i}/share/man:${MANPATH}"
  done
fi

export PATH

alias curl="nocorrect curl"
alias git="nocorrect git"
alias gwd="git diff --word-diff"
alias tmux="tmux -u -2"
alias notebook="(mkdir -p ~/work/notebook; cd ~/work/notebook; ipython notebook --pylab=inline --ip=\"*\" --port=$IPN_PORT --MappingKernelManager.time_to_dead=10 --MappingKernelManager.first_beat=3)"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

# Workaround for update failure
export ZSH=$HOME/.oh-my-zsh

if [ -f "$HOME/.local.zshrc" ]; then
  source "$HOME/.local.zshrc"
fi



alias -g L="|less"
alias -g TL='| tail -20'
alias -g NUL="> /dev/null 2>&1"

